apiVersion: batch/v1
kind: Job
metadata:
  name: gh-data-extract-gh-job
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/gcp-credentials/user-gcp-sa.json
#tag::newenvs[]
        - name: BUCKET
          value: kf-gh-demo-kustomized
        - name: PROJECT
          value: my-kf-project
#end::newenvs[]
        image: gcr.io/boos-demo-projects-are-rad/kf-steps/bq-extract:v8
        name: gh-data-extract-gh-job
        volumeMounts:
        - mountPath: /secret/gcp-credentials
          name: secret-volume
          readOnly: true
      restartPolicy: OnFailure
      volumes:
      - name: secret-volume
        secret:
          secretName: user-gcp-sa
