apiVersion: batch/v1
kind: Job
metadata:
  name: myjob-gh-job
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - name: myjob-gh-job
          image: bq-extract
          volumeMounts:
            - name: secret-volume
              mountPath: /secret/gcp-credentials
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secret/gcp-credentials/user-gcp-sa.json
            - name: BUCKET
              value: $(bucket)
      restartPolicy: OnFailure
      volumes:
        - name: secret-volume
          secret:
            secretName: user-gcp-sa
