varReference:
- path: metadata/name
  kind: Job
- path: spec/template/spec/containers/name
  kind: Job
- path: spec/template/spec/containers/image
  kind: Job
- path: spec/template/spec/containers/env/value
  kind: Job
- path: spec/template/spec/volumes/secret/secretName
  kind: Job