kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-1
  namespace: kubeflow
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
